export const CoffeeList = [
  {
    id: 1,
    title: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 6.5,
    tags: ["Tradicional"],
    image: "/public/assets/coffees/expresso-tradicional.svg",
  },
  {
    id: 2,
    title: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 6.9,
    tags: ["Tradicional"],
    image: "/public/assets/coffees/expresso-americano.svg",
  },
  {
    id: 3,
    title: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: 7.5,
    tags: ["Tradicional"],
    image: "/public/assets/coffees/expresso-cremoso.svg",
  },
  {
    id: 4,
    title: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 7.9,
    tags: ["Tradicional", "Gelado"],
    image: "/public/assets/coffees/expresso-gelado.svg",
  },
  {
    id: 5,
    title: "Café com leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 8.5,
    tags: ["Tradicional", "Com leite"],
    image: "/public/assets/coffees/cafe-leite.svg",
  },
  {
    id: 6,
    title: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosas",
    price: 8.9,
    tags: ["Tradicional", "Com Leite"],
    image: "/public/assets/coffees/latte.svg",
  },
  {
    id: 7,
    title: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 9.2,
    tags: ["Tradicional", "Com leite"],
    image: "/public/assets/coffees/capuccino.svg",
  },
  {
    id: 8,
    title: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: 8.7,
    tags: ["Tradicional", "Com leite"],
    image: "/public/assets/coffees/macchiato.svg",
  },
  {
    id: 9,
    title: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 9.5,
    tags: ["Tradicional", "Com leite"],
    image: "/public/assets/coffees/mocaccino.svg",
  },
  {
    id: 10,
    title: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 9.9,
    tags: ["Tradicional", "Com leite"],
    image: "/public/assets/coffees/chocolate-quente.svg",
  },
  {
    id: 11,
    title: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 11.5,
    tags: ["Tradicional", "Alcoólico", "Gelado"],
    image: "/public/assets/coffees/cubano.svg",
  },
  {
    id: 12,
    title: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 10.5,
    tags: ["Especial"],
    image: "/public/assets/coffees/havaiano.svg",
  },
  {
    id: 13,
    title: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 10.9,
    tags: ["Especial"],
    image: "/public/assets/coffees/arabe.svg",
  },
  {
    id: 14,
    title: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 12.5,
    tags: ["Especial", "Alcoólico"],
    image: "/public/assets/coffees/irlandes.svg",
  },
];
